#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
textcolor(RED);
gotoxy(23,6);
cprintf("======================================");
gotoxy(23 ,7);
cprintf("||   THIS IS MY SECOND PROGRAM IN C ||");
gotoxy(23 ,8);
cprintf("======================================");
gotoxy(5,10);
cprintf("======================================");
gotoxy(5 ,11);
cprintf("||   THIS IS MY SECOND PROGRAM IN C ||");
gotoxy(5 ,12);
cprintf("======================================");
gotoxy(40,10);
cprintf("======================================");
gotoxy(40 ,11);
cprintf("||   THIS IS MY SECOND PROGRAM IN C ||");
gotoxy(40 ,12);
cprintf("======================================");
gotoxy(23,14);
cprintf("======================================");
gotoxy(23 ,15);
cprintf("||   THIS IS MY SECOND PROGRAM IN C ||");
gotoxy(23 ,16);
cprintf("======================================");
getch();
}